PUT http://localhost:5000/profiles/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvZSIsImlhdCI6MTY0MzgxODkxM30.WFZstYfzlNMblrZg5fS9v-fXlLtPOXwD6qZQjOVrXBY
Content-Type: application/json

{
    "name": "Joe Profile Updated SECOND TIME", 
    "profilePhoto": "photo2.jpg"
}