POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "joe",
    "password": "password",
    "email": "joe@gmail.com",
    "companyName": "joeCompany",
    "companyLogo": "joe.jpg",
    "profileName": "Joe Profile",
    "profilePhoto": "joeprofile.jpg",
    "profileStatus": "pending"
}